services:
  - type: web
    name: raaj-bearings
    runtime: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
